version: '3'
services:
  converter-web:
    build: .
    ports:
      - "8001:8000"
    networks:
      - shared-network
    volumes:
      - .:/app  # 掛載整個專案目錄
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app", "--log-level", "error"]

networks:
  shared-network:
    external: true
